export const playerStats = {
  defaultStats: {
    warrior: {
      str: 16,
      dex: 12,
      con: 14,
      int: 10,
      wis: 8,
      cha: 10,
      level: 1,
      exp: 0,
      move: 82,
      ac: 15,
      mana: 0,
    },
    magicUser: {
      str: 8,
      dex: 12,
      con: 10,
      int: 16,
      wis: 10,
      cha: 12,
      level: 1,
      exp: 0,
      move: 82,
      ac: 10,
      mana: 20,
    },
    cleric: {
      str: 12,
      dex: 10,
      con: 14,
      int: 10,
      wis: 16,
      cha: 14,
      level: 1,
      exp: 0,
      move: 82,
      ac: 12,
      mana: 20,
    },
    thief: {
      str: 14,
      dex: 16,
      con: 12,
      int: 12,
      wis: 10,
      cha: 8,
      level: 1,
      exp: 0,
      move: 82,
      ac: 15,
      mana: 0,
    },
  },
};

export default playerStats;
